version: "3.3"

services:
  rpi-season-screen-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: "${USER_ID}"
        HOST_GID: "${GROUP_ID}"
        HOST_GN: "${GROUP_NAME}"
    
    image: "${IMAGE_NAME:-rpi-season-screen:local}"
    container_name: "${CONTAINER_NAME:-rpi-season-screen}"
    privileged: true
    volumes:
      - type: bind
        source: "${PWD}/../"
        target: "/builder/rpi-season-screen"
